### ISSUE TITLE
MDX

### ISSUE THREAD

**Issue by Bowriverstudio** [bhishp/storybook-formik#11]
Thank you for making this addon.  It is amazing!

I've got this working perfectly with CFS stories, but not MDX.  Do you know how to get it to work in that format?

**Comment by bhishp** [comment]
I'm afraid that i haven't tried anything with mdx or have experience even setting up storybook book with mdx at all. If you can point me in the right direction of storybook/mdx setup then I'll see if there's something that can be done to easily integrate this addon.

On a side note, I am half way through refactoring the code and test compatibility with sb6.x so the refactored code may fare better too


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Bowriverstudio** [comment]
Hello Bhishp,

When I just used `npx sb init` on a new project and it worked perfectly.  

I just tried it again and your addon worked perfectly!  

FormikTest is from: https://github.com/gopinav/React-Formik-Tutorials/blob/master/formik-controls-demo/src/components/FormikContainer.js

```
import {
  Meta,
  Story,
  Canvas,
  ArgsTable,
  Description,
} from "@storybook/addon-docs/blocks";
import FormikTest from "../FormikTest";

<Meta title="Formik/Forms/FormikTest" component={FormikTest} />

# FormikTest

<Description of={FormikTest} />

#

<Canvas>
  <Story name="FormikTest">
    <FormikTest />
  </Story>
</Canvas>

## Props

<ArgsTable of={FormikTest} />

```

Thanks again,
Maurice
