### ISSUE TITLE
Code example is not up to date.

### ISSUE THREAD

**Issue by DonikaV** [bhishp/storybook-formik#17]
Storybook has a new API.

```
import { storiesOf } from '@storybook/react';
import withFormik from 'storybook-formik';

import PersonalInfoSubform from '<your_component_path>/PersonalInfoSubform';

storiesOf('Example', module)
  .addDecorator(withFormik)
  .add('default', () => <PersonalInfoSubform />, {
    formik: {
      initialValues: {
        forename: 'John',
        surname: 'Johnerson',
      },
    },
  }); 

```

This code from the example won't work in the new version.
Any examples of how I can setup my storybook with a new API and this module?
Thanks in advance.

**Comment by bhishp** [comment]
Hey @DonikaV there is a section in the README for using the newer CSF (Component Storybook Format) - https://github.com/bhishp/storybook-formik#using-csf

Pasted here for reference:

```jsx
export const formik = () => (
  <div>
    <Field name="foo" />
  </div>
);

formik.story = {
  decorators: [withFormik],
  parameters: {
    formik: {
      initialValues: {
        foo: 'Initialized'
      }
    }
  }
};
```

But I'm also going to raise a PR to update the examples to remove usage of `storiesOf` syntax so the repo is more up to date.

I hope this helps with your case, let me know if you have an issues.

**Comment by bhishp** [comment]
As mentioned, I have raised and merged a PR here that shows how to use the new story format - https://github.com/bhishp/storybook-formik/pull/18

Hopefully this clarifies things for you but feel free to re-open the issue if you are still having problems

**Comment by DonikaV** [comment]
@bhishp cool! thanks! :)

**Comment by DonikaV** [comment]
One question, can I add somehow className to the decorator? 
```
export default {
  title: "Form/TextInputs",
  component: PersonalInfoSubform,
  decorators: [withFormik],
  parameters: {
    formik: {
      initialValues: {
        firstName: "",
        email: "",
      },
      validationSchema: FormSchema,
      onSubmit: (v) => console.log("I want to log these... ", v),
    },
  },
};
const Template = (args) => <PersonalInfoSubform {...args} />;
export const Default = Template.bind({});

```

**Comment by bhishp** [comment]
Classname as in a css className prop? And when you say to the decorator do you mean the underlying <Formik> component that wraps your components?

Right now I think and className prop dropped in parameters would just be ignored but maybe we could add a parameter for passing on extra props.

What would your use case be?



Sent from my Galaxy



-------- Original message --------
From: Valeriy Donika ***@***.***>
Date: 02/04/2021 12:42 (GMT+00:00)
To: bhishp/storybook-formik ***@***.***>
Cc: Bhish ***@***.***>, Mention ***@***.***>
Subject: Re: [bhishp/storybook-formik] Code example is not up to date. (#17)


One question, can I add somehow className to the decorator?

export default {
  title: "Form/TextInputs",
  component: PersonalInfoSubform,
  decorators: [withFormik],
  parameters: {
    formik: {
      initialValues: {
        firstName: "",
        email: "",
      },
      validationSchema: FormSchema,
      onSubmit: (v) => console.log("I want to log these... ", v),
    },
  },
};
const Template = (args) => <PersonalInfoSubform {...args} />;
export const Default = Template.bind({});

**Comment by DonikaV** [comment]
Because when I add forms to my storybook with this addon I can see <form> tag, and I would like to pass somehow **className** and **name** to that tag. If it is possible.

**Comment by bhishp** [comment]
Sorry, I don't quite understand. If you could provide a code example to help show your intention that would be helpful

**Comment by DonikaV** [comment]
![image](https://user-images.githubusercontent.com/26111842/113562065-29cde500-960e-11eb-8e90-f45d90c2c248.png)
![image](https://user-images.githubusercontent.com/26111842/113562100-35b9a700-960e-11eb-85e6-e33ba38e6c51.png)

Does this Form tag come from withFormik? How I can add some attributes to that tag?
