### ISSUE TITLE
How would I set an error message for a field?

### ISSUE THREAD

**Issue by sambunting** [bhishp/storybook-formik#26]
Hi. Not too sure if this is a bug or if I'm not doing something right?

I have a component which is a custom `<Field />` from Formik - for one of the stories, I'd like to display the field error message when it is initialised/loaded. 

At the moment, I have this - but it doesn't seem to work:

```jsx
const defaultArgs = {
  name: 'story',
  label: 'Story Date Input',
};

export const Error = (args) => <DateInput {...args} />;
Error.args = { ...defaultArgs };
Error.parameters = {
  formik: {
    initialValues: {
      story: '',
    },
    errors: {
      story: 'Error Message!',
    },
    touched: {
      story: true,
    },
  },
};
```

Not too sure if it's me, Formik or something else altogether. Are the `errors` and `touched` properties read-only maybe?

**Comment by bhishp** [comment]
Apologies but its been a long time since I've used Formik on a daily basis so my knowledge is a bit rusty. However, it looks like there is an `initialErrors` prop on the Formik component too, could that be what you're after?

https://formik.org/docs/api/formik#initialerrors-formikerrorsvalues

**Comment by sambunting** [comment]
Ahhhh I must have missed that one!! Yes! It looks like that works!

Working code looks something like this:
```jsx
const defaultArgs = {
  name: 'story',
  label: 'Story Date Input',
};

export const Error = (args) => <DateInput {...args} />;
Error.args = { ...defaultArgs };
Error.parameters = {
  formik: {
    initialErrors: {
      story: 'Error Message!',
    },
    initialTouched: {
      story: true,
    },
  },
};
```

[`initialTouched`](https://formik.org/docs/api/formik#initialtouched-formiktouchedvalues) is also something else that exists, and that's there as the error message in my component will only show if it's true.

Thanks for pointing it out to me! 😄
