### ISSUE TITLE
BUG: Remove white background to support storybook dark theme

### ISSUE THREAD

**Issue by alexvandervegt** [bhishp/storybook-formik#27]
At the moment the plugin is not usable in the dark mode because of the white backgrounds.

See printscreen:
<img width="1682" alt="Screenshot 2021-10-07 at 09 59 35" src="https://user-images.githubusercontent.com/3672692/136343860-7877515d-a4bc-44d1-867b-2f9e5d7fe829.png">

When the white backgrounds are removed using inspection mode it gets usable see
<img width="1677" alt="Screenshot 2021-10-07 at 10 00 17" src="https://user-images.githubusercontent.com/3672692/136343975-a0cbc6cb-47fa-4399-a111-ab9eac7c0589.png">
:

**Comment by bhishp** [comment]
Hi @alexvandervegt thanks for raising this issue, I have been very busy recently so I haven't had time to fix this bug and may not get any time soon but happy to accept a PR that addresses this. Cheers, Bhish

**Comment by alexvandervegt** [comment]
Done

**Comment by bhishp** [comment]
Fix released in v2.2.0 - https://www.npmjs.com/package/storybook-formik/v/2.2.0

Thanks for contributing @alexvandervegt
