### ISSUE TITLE
Signup example does not show updates and submits in the formik tab

### ISSUE THREAD

**Issue by warreee** [bhishp/storybook-formik#29]
In Singup example submitting does not seem to update the Formik tab:
<img width="1914" alt="Screenshot 2021-12-20 at 12 08 06" src="https://user-images.githubusercontent.com/4020491/146758008-936365a7-0fb5-454e-871e-07ccb83e46b3.png">

Is this expected behavior?

**Comment by bhishp** [comment]
This is expected. The Signup form is a full Formik form (it has a `<Formik>` component around it) and is simply there for demonstration purposes of how sub-forms can be composed into larger forms. The fact that it has a <Formik> wrapper means that all form state is held within its internal context-provider, therefore is not accessible via the add-on.

Maybe? there is a way to intercept the internal context and then replay it to the storybook add-on but when I explored it previously there was no possible way it could be done as far as I could tell...

I hope that helps explain

**Comment by warreee** [comment]
Alright, @bhishp, this explains, thanks!
