### ISSUE TITLE
Jest - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by martinffx** [bhishp/storybook-formik#3]
When importing a "view" from storybook into a jest test I get an error: Cannot use import statement outside a module

```
// stories.js
import React from 'react';
import {action} from '@storybook/addon-actions';
import withFormik from 'storybook-formik';

import {
  Component,
  ComponentSchema
} from './Component';

export default {
  component: Component,
  title: 'Component',
  decorators: [lwithFormik],
  parameters: {
    formik: {
      initialValues: {
        name: ''
      },
      validationSchema: ComponentSchema,
      onSubmit: action('SUBMIT'),
    },
  },
};

export const Default = () => (
  <Component />
);
```

```
// test.js
import React from 'react';
import {mount} from 'enzyme';
import {Formik} from 'formik';

import {Default} from './stories';

describe('Component', () => {
  test('Component does things, () => {
    const wrapper = mount(
      <AppProvider>
        <Formik
          initialValues={{
            name: '',
          }}
        >
          <Default />
        </Formik>
      </AppProvider>,
    );
  });
```

To get around this I dynamically import the `withFormik`:

```
// stories.js
...
const loadWithFormik = async () => await import('storybook-formik');

export default {
  component: Component,
  title: 'Component',
  decorators: [loadWithFormik()],
  ...
};
...
```

**Comment by martinffx** [comment]
So this obviously never worked, the actual solution was to include :`"transformIgnorePatterns": ["node_modules/(?!(storybook-formik)/)"]` in the jest config.

**Comment by sambunting** [comment]
Thanks for the fix!  

Just adding that something else I needed to do to get this to work was I needed to change the name of my Babel file from `.babelrc` to `babel.config.js` if you were using Babel like me.

**Comment by jonasschultheiss** [comment]
i really dont get it.
my babel file is named `babel.config.js`. i have `"transformIgnorePatterns": ["node_modules/(?!(storybook-formik)/)"]` in my jest config and it still doesn't work, printing the same error.

**Comment by jonasschultheiss** [comment]
got some progress. i removed all other entries from the transformIgnorePatterns array except the one mentioned in my previous comment.
I now have a new error, that makes even less sense to me:
```
  ● TextField › should display a disabled icon, even if the input is valid

    TypeError: Cannot read property 'getFieldProps' of undefined

      37 | export const TextField: FC<TextFieldProperties> = (properties) => {
      38 |   const { variant, id, name, status, indicateLoading, required, disabled, placeholder } = properties;
    > 39 |   const [field, meta] = useField(name);
         |                         ^
      40 |
      41 |   const textColorFromStatus = (): string | void => {
      42 |     if ((status === 'valid' && !disabled) || (!meta.error && !disabled)) {
```

**Comment by EnzoVezzaro** [comment]
Hi @jonasschultheiss did you manage to solve this?

**Comment by jonasschultheiss** [comment]
Hey @EnzoVezzaro 
I'm a bit lost, as I haven't touched my project in a long time now. I cloned it again and run the tests. They work, but I can't help you on why and how as I lack the understanding of the issue right now.
You can checkout my repo and see for yourself if you want:
https://github.com/prsm/refracted/tree/develop
The error code came from the file `textField.test.tsx`

If the code doesn't help, ask me something more concrete and I may be able to help
